/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { supabase } from "../../lib/supabase";

const Header: React.FC = () => {
  return (
    <header className="flex gap-5 px-16 py-3 w-full bg-white border-b border-solid border-neutral-200 max-md:flex-wrap max-md:px-5 max-md:max-w-full">
      <h1 className="flex-auto my-auto text-xl font-semibold tracking-normal leading-8 text-black">
        Gym up Stats - Adminstation
      </h1>
      <div className="flex gap-5 justify-between">
        <div className="flex gap-3">
          
      <button onClick={() =>{
        supabase.auth.signOut()
      }} className="text-black bg-gray-200 p-4 max-h-20 rounded-xl " >Sign out</button>

      
          
        </div>
        
      </div>
    </header>
  );
};

export default Header;
