/**
 * This code was generated by Builder.io.
 */
import React from "react";

const SearchBar: React.FC = () => {
  return (
    <div className="flex gap-3 self-end px-3 py-2 mt-8 mr-20 text-base leading-6 whitespace-nowrap bg-white rounded-lg border border-solid border-neutral-200 text-zinc-500 max-md:mr-2.5">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/eb24ed642213c596572a68bfb4b518ecbe321f5fb33b43e09fadd9662de7f9f0?apiKey=7a3a7c63ac864902b9d3b9e8514feb0a&"
        className="shrink-0 w-6 aspect-square"
        alt="Search icon"
      />
      <input
        type="text"
        placeholder="Search..."
        className="flex-1 text-ellipsis bg-transparent border-none outline-none"
      />
    </div>
  );
};

export default SearchBar;
