/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface StatCardProps {
  title: string;
  value: string;
  change: string;
}

const StatCard: React.FC<StatCardProps> = ({ title, value, change }) => {
  return (
    <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
      <div className="flex flex-col grow p-6 w-full text-base font-semibold leading-6 text-black bg-white rounded-lg border border-solid shadow-sm border-neutral-200 max-md:px-5 max-md:mt-8 max-md:max-w-full">
        <div className="max-md:max-w-full">{title}</div>
        <div className="mt-4 text-4xl tracking-tighter leading-10 max-md:max-w-full">
          {value}
        </div>
        <div className="mt-4 font-medium text-zinc-500 max-md:max-w-full">
          {change}
        </div>
      </div>
    </div>
  );
};

export default StatCard;
