/**
 * This code was generated by Builder.io.
 */
import React from "react";

const UserChart: React.FC = () => {
  return (
    <div className="flex flex-col w-[59%] max-md:ml-0 max-md:w-full">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/f84efb03c07d367d65bb7c385823fc010c001b57b5782f18c21201330113a300?apiKey=7a3a7c63ac864902b9d3b9e8514feb0a&"
        className="grow w-full border border-solid shadow-sm aspect-[1.64] border-neutral-200 max-md:mt-8 max-md:max-w-full"
        alt="User statistics chart"
      />
    </div>
  );
};

export default UserChart;
