/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import SearchBar from "./SearchBar";
import StatCard from "./StatCard";
import UserChart from "./UserChart";
import UserList from "./UserList";
import UserForm from "./UserForm";
import BackupControls from "./BackupControls";
import { useAuth } from "../../lib/AuthProvider";

const AdminDashboard: React.FC = () => {
  const session = useAuth()
  if(!session){
    return;
  }
  return (
    <div className="flex flex-col justify-center pb-3.5 bg-black">
      <Header />
      <SearchBar />
      <main className="flex flex-col px-20 mt-8 w-full max-md:px-5 max-md:max-w-full">
        <section className="max-md:max-w-full">
          <div className="flex gap-5 max-md:flex-col max-md:gap-0">
            <StatCard
              title="Users quantity"
              value="2,405"
              change="+33% month over month"
            />
            <StatCard
              title="Session created"
              value="10,353"
              change="8% month over month"
            />
          </div>
        </section>
        <section className="mt-8 max-md:max-w-full">
          <div className="flex gap-5 max-md:flex-col max-md:gap-0">
            <UserChart />
            <UserList />
          </div>
        </section>
        <section className="mt-7 max-w-full w-[857px]">
          <div className="flex gap-5 max-md:flex-col max-md:gap-0">
            <UserForm />
            <BackupControls />
          </div>
        </section>
      </main>
    </div>
  );
};

export default AdminDashboard;
