/**
 * This code was generated by Builder.io.
 */
import React from "react";

const BackupControls: React.FC = () => {
  return (
    <div className="flex flex-col ml-5 w-[34%] max-md:ml-0 max-md:w-full">
      <div className="flex flex-col grow mt-96 text-base font-medium leading-6 max-md:mt-10">
        <button className="justify-center px-4 py-2 text-black rounded-lg bg-zinc-100">
          Choose data to restore system
        </button>
        <button className="justify-center px-4 py-2 mt-4 text-white bg-black rounded-lg">
          Backup data to your computer
        </button>
      </div>
    </div>
  );
};

export default BackupControls;
