/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Header: React.FC = () => {
  return (
    <header className="flex gap-5 px-16 py-3 w-full bg-white border-b border-solid border-neutral-200 max-md:flex-wrap max-md:px-5 max-md:max-w-full">
      <h1 className="flex-auto my-auto text-xl font-semibold tracking-normal leading-8 text-black">
        Gym up Stats - Adminstation
      </h1>
      <div className="flex gap-5 justify-between">
        <div className="flex gap-3">
          <div className="flex justify-center items-center px-4 py-2 rounded-lg bg-zinc-100">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/8d63a5fc2c5586a61568dadfd60e7fcc434fcc26de3d8c0acfaf3a36beb5dbc5?apiKey=7a3a7c63ac864902b9d3b9e8514feb0a&"
              className="w-6 aspect-square"
              alt=""
            />
          </div>
          <button className="justify-center px-4 py-2 text-base font-medium leading-6 text-white whitespace-nowrap bg-black rounded-lg">
            Share
          </button>
        </div>
        <div className="flex gap-2">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/1986e59ea044ede390acb792f8b19d0ac4678204d224ee01d89dbe0bbd4a2358?apiKey=7a3a7c63ac864902b9d3b9e8514feb0a&"
            className="shrink-0 w-10 aspect-square"
            alt="User avatar"
          />
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/245de0f0c45e9a16d332378bca3d5ff08d50f4cf294ae90ec616490145201c21?apiKey=7a3a7c63ac864902b9d3b9e8514feb0a&"
            className="shrink-0 my-auto w-6 aspect-square"
            alt="Dropdown icon"
          />
        </div>
      </div>
    </header>
  );
};

export default Header;
