/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface User {
  name: string;
  email: string;
  avatar: string;
}

const users: User[] = [
  {
    name: "Helena",
    email: "email@figmasfakedomain.net",
    avatar:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/4d8c2c74b789b9541f45e2384cb3483abcdcdeb23d315a367d176f2884eb50a9?apiKey=7a3a7c63ac864902b9d3b9e8514feb0a&",
  },
  {
    name: "Oscar",
    email: "email@figmasfakedomain.net",
    avatar:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/b94095bbf738d2ecd7a4f750f0708cca392887b993aa74c79e886981d5fc9515?apiKey=7a3a7c63ac864902b9d3b9e8514feb0a&",
  },
  {
    name: "Daniel",
    email: "email@figmasfakedomain.net",
    avatar:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/75a33c5dcd2527d6f65ec7b5c8582746d3f90aa24ab02a209dce38f12c438b31?apiKey=7a3a7c63ac864902b9d3b9e8514feb0a&",
  },
  {
    name: "Daniel Jay Park",
    email: "email@figmasfakedomain.net",
    avatar:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/6ec4365808505e773150e19d56eb92617ce50d05395408c418f9bfb1ffebe32b?apiKey=7a3a7c63ac864902b9d3b9e8514feb0a&",
  },
  {
    name: "Mark Rojas",
    email: "email@figmasfakedomain.net",
    avatar:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/e1d34c048d06eefbb10527608042bd0019691edfcea40859506dee258f461468?apiKey=7a3a7c63ac864902b9d3b9e8514feb0a&",
  },
];

const UserList: React.FC = () => {
  return (
    <div className="flex flex-col ml-5 w-[41%] max-md:ml-0 max-md:w-full">
      <div className="flex flex-col grow p-6 w-full text-base leading-6 bg-white rounded-lg border border-solid shadow-sm border-neutral-200 max-md:px-5 max-md:mt-8 max-md:max-w-full">
        <h2 className="font-semibold text-black max-md:max-w-full">User</h2>
        {users.map((user, index) => (
          <div
            key={index}
            className="flex gap-4 py-3 mt-4 whitespace-nowrap rounded-lg max-md:flex-wrap"
          >
            <img
              loading="lazy"
              src={user.avatar}
              className="shrink-0 w-12 aspect-square"
              alt={`${user.name}'s avatar`}
            />
            <div className="flex flex-col flex-1">
              <div className="font-medium text-black">{user.name}</div>
              <div className="text-ellipsis text-zinc-700">{user.email}</div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default UserList;
